FROM public.ecr.aws/lambda/python:3.12.2024.08.09.13

# Copy requirements.txt
COPY ./requirements.txt ${LAMBDA_TASK_ROOT}

# Install the specified packages
RUN pip install -r requirements.txt

# Copy function code
COPY ./app/constants ${LAMBDA_TASK_ROOT}/app/constants 
COPY ./app/modules ${LAMBDA_TASK_ROOT}/app/modules
COPY ./app/routers ${LAMBDA_TASK_ROOT}/app/routers
COPY ./app/static ${LAMBDA_TASK_ROOT}/app/static

COPY ./app/app.py ${LAMBDA_TASK_ROOT}/app
COPY ./app/run.py ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler
CMD [ "run.run" ]