name: Infracost analysis directly over plan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - master
  workflow_dispatch:      # Allows you to manually trigger the workflow

env:
  TF_WORKING_DIR: infra

permissions:
  contents: read

jobs:
  infracost:
    name: infracost
    runs-on: ubuntu-latest

    steps:
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: '${{ github.event.pull_request.base.ref }}'

      # github.event.pull_request.base.ref returns null when no present pull_request (eg. when triggered manually), and the checkout defaults to the default/main branch

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: {{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: {{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: eu-north-1

      # Generate Infracost JSON file as the baseline.
      - name: Generate plan
        id: plan_step
        uses: ./.github/actions/get-terraform-plan
        with:
          tf_working_dir: ${{ env.TF_WORKING_DIR }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Display the path to tfplan.json
      - run: |
          echo 'Terraform plan path: ${{ steps.plan_step.outputs.tfplan_path }}'

      - name: Upload plan as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-json
          path: ${{ steps.plan_step.outputs.tfplan_path }}

      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Infracost JSON
        run: infracost breakdown --path ${{ steps.plan_step.outputs.tfplan_path }} --format json --out-file /tmp/infracost-base.json

      - name: Upload Infracost baseline as artifact
        uses: actions/upload-artifact@v4
        with:
          name: infracost-base-json
          path: /tmp/infracost-base.json

      - name: Generate Infracost cost estimate baseline (HTML)
        if: ${{ !github.event.pull_request }}
        run: |
          infracost breakdown --path=${{ steps.plan_step.outputs.tfplan_path }} \
                              --format=html \
                              --out-file=/tmp/infracost-base.html

      - name: Upload Infracost baseline as artifact
        if: ${{ !github.event.pull_request }}
        uses: actions/upload-artifact@v4
        with:
          name: infracost-base-html
          path: /tmp/infracost-base.html

      - name: Post Infracost comment
        if: ${{ github.event.pull_request }}
        run: |
          infracost comment github --path /tmp/infracost-base.json \
                                    --repo $GITHUB_REPOSITORY \
                                    --github-token ${{github.token}} \
                                    --pull-request ${{github.event.pull_request.number}} \
                                    --behavior update