name: Terraform Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Cache plugin dir
        uses: actions/cache@v4
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}
  
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
            tflint_wrapper: true
  
      - name: Init TFLint
        run: tflint --init
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}
  
      - name: Run TFLint
        working-directory: infra
        run: tflint -f compact --recursive

      # # Step 5: Run tfsec (security checks for Terraform code)
      # - name: Run tfsec
      #   working-directory: infra
      #   run: |
      #     tfsec

      # # Step 6: Run Checkov (misconfiguration checks)
      # - name: Run Checkov
      #   working-directory: infra
      #   run: |
      #     checkov

      # # Step 7: Run Infracost (cost estimation)
      # - name: Run Infracost
      #   working-directory: infra
      #   run: |
      #     infracost breakdown --format json > infracost_output.json
      #     infracost show --path infracost_output.json --format table
