name: Get Terraform Outputs

# Specify when the workflow should run
on:
  push:
    branches:
      - master
  workflow_dispatch:  # Allows you to manually trigger the workflow


jobs:
  extract-terraform-outputs:
    runs-on: ubuntu-latest

    defaults:
        run:
            working-directory: infra
            shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
            terraform_wrapper: false

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init

      - name: Get Specific Terraform Outputs
        id: terraform-outputs
        run: |
            output=$(terraform output vpc_id)
            echo $output
      