name: Retrieve Terraform Outputs

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  extract-outputs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Get Terraform Outputs Action
        uses: ./.github/actions/get-terraform-outputs
        with:
          outputs_of_interest: "region ecr_repository_name ecs_service_name ecs_cluster_name ecs_task_definition ecs_container_name"
          working_directory: "infra"

      - name: Display Terraform Outputs File
        run: echo "${{ env.region }}"   # By appending this string to $GITHUB_ENV, it instructs GitHub Actions to treat output_file as an output environment variable accessible across steps.
                                                                    # GitHub automatically reads and loads variables from $GITHUB_ENV, so output_file becomes accessible to subsequent steps as an environment variable.
